apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: product-destination-rules
  namespace: shoppingportal    
spec:
  host: product-svc.shoppingportal.svc.cluster.local
  subsets:
  - name: stable
    labels:
      version: v1
