apiVersion: v1
kind: Secret
metadata:
  name: shoppingcartsecret
  namespace: shoppingportal
type: Opaque
data:
  product_app_base_url: aHR0cDovL3Byb2R1Y3Qtc3ZjL3Byb2R1Y3Rtcw==
  shoppingcart_app_base_url: aHR0cDovL3Nob3BwaW5nY2FydC1zdmMvc2hvcHBpbmdjYXJ0bXMK