apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: orderms-deploy
  namespace: shoppingportal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orderms
      zone: prod
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: orderms
        version: v1
        release: stable
        tier: be
        zone: prod
        managed-by: m2
    spec:
      containers:
        - name: orderms-ctr
          image: metamagicglobal/orderservice_k8
          imagePullPolicy: Always
          ports:
          - containerPort: 8082
          env:
          - name: MONO_HOST
            valueFrom:
              secretKeyRef: 
                name: mongosecret
                key: mongohost
          - name: MONO_PORT
            valueFrom:
              secretKeyRef: 
                name: mongosecret
                key: mongoport
          - name: PRODUCT_APP_BASE_URL
            valueFrom:
              secretKeyRef: 
                name: shoppingcartsecret
                key: product_app_base_url                                