apiVersion: v1
kind: Service
metadata:
  name: orderui-svc
  namespace: shoppingportal
  labels:
    name: orderuisvc
spec:
  selector:
        name: orderui
        version: "1.0.0"
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: my-http-port